### ISSUE TITLE
Question of the time cost to run an epoch!

### ISSUE THREAD

**Issue by SivanHu** [Soldelli/VLG-Net#4]
Excuse me, How long does an epoch take?  I cannot see the evaluation result of an epoch for more than two hours. Maybe there's something wrong with me.

**Comment by Soldelli** [comment]
Hi, can you please double check your environment against the provided yml? 
I have seen such problem with problematic environments. 

Make sure you are using the same version of the major libraries. 
Feel free to reach out any time. 

PS: all trainings should complete within 24hrs maximum on a single v100 32GB. 
Once the training starts, you should see updates regarding the status every minute or so.
